#
# Module manifest for module 'Monocle'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 05/10/2016
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Monocle.psm1'

    # Version number of this module.
    ModuleVersion = '1.3.4'

    # ID used to uniquely identify this module
    GUID = '9dc3c8a1-664d-4253-a5d2-920250d3a15f'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2016-2020 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'PowerShell Web Automation module, made to make automating and testing websites easier'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'web', 'automation', 'testing', 'ie', 'internet-explorer', 'websites', 'chrome', '2fa',
                'firefox', 'selenium', 'cross-platform', 'PSEdition_Core', 'PSEdition_Desktop', 'linux', 'google-chrome',
                'edge', 'chromium')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Monocle/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Monocle'

        }
    }
}

